// Generated by tools/gen_protocol.py - DO NOT EDIT BY HAND.
//
// Ultimate Command Interface constants for KickAssembler.
//
//     #import "uci_protocol.asm"
//     lda #uci.UCI_TARGET_DOS1
//
// The code itself is not linkable from KickAssembler; use the
// standalone binary in bindings/blob, which needs no linking at all.
//
// SPDX-License-Identifier: MIT

.filenamespace uci

// ---- Register map ----
// UCI I/O registers. The block is mapped at $DF1B-$DF1F and overlays the
// last five REU registers. Mapping is optional and is enabled in the
// Ultimate 'Command Interface' configuration menu.
.label UCI_REG_BUSID              = $DF1B  // R   SoftwareIEC bus ID (0 = unset)
.label UCI_REG_CONTROL            = $DF1C  // W   Control register
.label UCI_REG_STATUS             = $DF1C  // R   Status register
.label UCI_REG_CMDDATA            = $DF1D  // W   Command data (write command bytes here)
.label UCI_REG_IDENT              = $DF1D  // R   Identification register
.label UCI_REG_RESPDATA           = $DF1E  // R   Response data queue
.label UCI_REG_STATDATA           = $DF1F  // R   Status data queue

// ---- Identification register values ----
// Read from UCI_REG_IDENT.
.label UCI_IDENT_IDLE             = $C9  // No interrupt pending
.label UCI_IDENT_IRQ              = $49  // Interrupt active (bit 7 cleared). FW 3.15+
.label UCI_IDENT_MASK             = $7F  // Mask off the IRQ bit before comparing
.label UCI_IDENT_VALUE            = $49  // Expected value after masking with UCI_IDENT_MASK

// ---- Control register bits ----
// Write-only. Always write a literal mask; never read-modify-write,
// because reading $DF1C returns the status register, not the control
// register.
.label UCI_CTRL_PUSH_CMD          = $01  // Submit the buffered command
.label UCI_CTRL_DATA_ACC          = $02  // Acknowledge / release the current data block
.label UCI_CTRL_ABORT             = $04  // Request abort of the running command
.label UCI_CTRL_CLR_ERR           = $08  // Clear the state-error flag
.label UCI_CTRL_IRQ               = $20  // Raise IRQ on completion (FW 3.15+, latched on push)
.label UCI_CTRL_TRIGGER           = $40  // Freeze the machine on the next $FF00 write (latched on push). NOT a transfer accelerator
.label UCI_CTRL_DMA               = $80  // Freeze the machine immediately (latched on push). NOT a transfer accelerator - see docs/uci.md

// ---- Status register bits ----
// Read from $DF1C.
.label UCI_STAT_CMD_BUSY          = $01  // A command is pending in command memory
.label UCI_STAT_DATA_ACC          = $02  // Data acknowledge seen by the Ultimate
.label UCI_STAT_ABORT_P           = $04  // Abort request still pending
.label UCI_STAT_ERROR             = $08  // State error: command pushed while not idle
.label UCI_STAT_STATE             = $30  // Protocol state mask
.label UCI_STAT_STAT_AV           = $40  // Status byte available at $DF1F
.label UCI_STAT_DATA_AV           = $80  // Response byte available at $DF1E

// ---- Protocol states ----
// Value of (status & UCI_STAT_STATE).
.label UCI_STATE_IDLE             = $00  // Ready to accept a command
.label UCI_STATE_BUSY             = $10  // Command submitted, Ultimate is working
.label UCI_STATE_DATA_LAST        = $20  // Data available, this is the final block
.label UCI_STATE_DATA_MORE        = $30  // Data available, more blocks follow

// ---- Queue sizes ----
// Hard limits enforced by the hardware. The three queue pointers all
// saturate on the LAST byte of their buffer rather than one past it, which
// costs a byte on the way in and can hang a naive reader on the way out -
// see docs/uci.md, 'Queue pointer saturation'.
.label UCI_MAX_COMMAND            = $0380  // Command queue size in bytes ($380)
.label UCI_MAX_RESPONSE           = $0380  // Response data queue size in bytes ($380)
.label UCI_MAX_STATUS             = $0100  // Status queue size in bytes ($100)
.label UCI_MAX_COMMAND_USABLE     = $037F  // Largest command the hardware can actually receive

// ---- Timeouts ----
// Budget for a status poll loop, in units of 256 polls. The core installs
// the default at bring-up, so the bounded-time guarantee holds without the
// caller doing anything; raise it around a command whose duration cannot
// be bounded and restore it after.
.label UCI_TIMEOUT_DEFAULT        = $C8  // Comfortable for local commands at any CPU speed
.label UCI_TIMEOUT_FOREVER        = $00  // Poll until the Ultimate answers, however long that takes

// ---- Targets ----
// First byte of every command. Only bits 0-3 select the target; bit 7 is
// the NO_REPLY flag (INFERRED from firmware).
.label UCI_TARGET_MASK            = $0F  // Target field of the first command byte
.label UCI_TARGET_NO_REPLY        = $80  // Fire-and-forget: skip the data/status phase
.label UCI_TARGET_DOS1            = $01  // Ultimate DOS instance 1
.label UCI_TARGET_DOS2            = $02  // Ultimate DOS instance 2
.label UCI_TARGET_NETWORK         = $03  // Network (TCP/UDP sockets)
.label UCI_TARGET_CONTROL         = $04  // Machine / cartridge control
.label UCI_TARGET_SOFTIEC         = $05  // SoftwareIEC bypass
.label UCI_TARGET_HTTP            = $06  // HTTP client (FW 3.15+)
.label UCI_TARGET_MAX             = $0F  // Highest addressable target

// ---- Commands common to every target ----
.label UCI_CMD_IDENTIFY           = $01  // Return an identification string. Cannot fail.

// ---- Ultimate DOS commands (targets $01/$02) ----
.label DOS_CMD_IDENTIFY           = $01
.label DOS_CMD_OPEN_FILE          = $02  // <attrib> <filename>
.label DOS_CMD_CLOSE_FILE         = $03
.label DOS_CMD_READ_DATA          = $04  // <len_lo> <len_hi>
.label DOS_CMD_WRITE_DATA         = $05  // <dummy> <dummy> <data...>
.label DOS_CMD_FILE_SEEK          = $06  // <pos32 LSB first>
.label DOS_CMD_FILE_INFO          = $07
.label DOS_CMD_FILE_STAT          = $08  // <filename>
.label DOS_CMD_DELETE_FILE        = $09  // <filename>
.label DOS_CMD_RENAME_FILE        = $0A  // <old> $00 <new>
.label DOS_CMD_COPY_FILE          = $0B  // <src> $00 <dst>
.label DOS_CMD_CHANGE_DIR         = $11  // <dirname>
.label DOS_CMD_GET_PATH           = $12
.label DOS_CMD_OPEN_DIR           = $13
.label DOS_CMD_READ_DIR           = $14
.label DOS_CMD_COPY_UI_PATH       = $15  // Deprecated since FW 3.0
.label DOS_CMD_CREATE_DIR         = $16  // <dirname>
.label DOS_CMD_COPY_HOME_PATH     = $17
.label DOS_CMD_LOAD_REU           = $21  // <addr32> <len32>
.label DOS_CMD_SAVE_REU           = $22  // <addr32> <len32>
.label DOS_CMD_MOUNT_DISK         = $23  // <id> <filename>
.label DOS_CMD_UMOUNT_DISK        = $24  // <id>
.label DOS_CMD_SWAP_DISK          = $25  // <id>
.label DOS_CMD_GET_TIME           = $26  // [fmt]
.label DOS_CMD_SET_TIME           = $27  // <Y-1900> <M> <D> <h> <m> <s>
.label DOS_CMD_ECHO               = $F0  // Echo the command back as data

// ---- DOS file open attributes ----
// Bit flags for DOS_CMD_OPEN_FILE.
.label DOS_FA_READ                = $01  // Open for reading
.label DOS_FA_WRITE               = $02  // Open for writing, do not truncate
.label DOS_FA_CREATE_NEW          = $04  // Create/truncate to zero bytes
.label DOS_FA_CREATE_ALWAYS       = $08  // May overwrite an existing file

// ---- DOS directory entry attributes ----
// First byte of each DOS_CMD_READ_DIR entry (FAT semantics).
.label DOS_ATTR_READONLY          = $01
.label DOS_ATTR_HIDDEN            = $02
.label DOS_ATTR_SYSTEM            = $04
.label DOS_ATTR_VOLUME            = $08
.label DOS_ATTR_DIR               = $10
.label DOS_ATTR_ARCHIVE           = $20

// ---- Network commands (target $03) ----
.label NET_CMD_IDENTIFY           = $01
.label NET_CMD_GET_INTERFACE_COUNT = $02
.label NET_CMD_GET_NETADDR        = $04  // <iface> -> 6 byte MAC
.label NET_CMD_GET_IPADDR         = $05  // <iface> -> 12 bytes ip/mask/gw
.label NET_CMD_SET_IPADDR         = $06  // <iface> <12 bytes>
.label NET_CMD_OPEN_TCP           = $07  // <port16> <host>
.label NET_CMD_OPEN_UDP           = $08  // <port16> <host>
.label NET_CMD_CLOSE_SOCKET       = $09  // <handle>
.label NET_CMD_READ_SOCKET        = $10  // <handle> <len16>
.label NET_CMD_WRITE_SOCKET       = $11  // <handle> <data...>
.label NET_CMD_LISTEN_START       = $12  // INFERRED: <port16>, not in the published spec
.label NET_CMD_LISTEN_STOP        = $13  // INFERRED: not in the published spec
.label NET_CMD_LISTEN_STATE       = $14  // INFERRED: not in the published spec
.label NET_CMD_LISTEN_SOCKET      = $15  // INFERRED: not in the published spec

// ---- Control commands (target $04) ----
.label CTRL_CMD_IDENTIFY          = $01
.label CTRL_CMD_READ_RTC          = $02  // INFERRED: firmware only, not in the published spec
.label CTRL_CMD_FINISH_CAPTURE    = $03
.label CTRL_CMD_FREEZE            = $05
.label CTRL_CMD_REBOOT            = $06  // Never replies: the C64 and the UCI are reset
.label CTRL_CMD_LOAD_REU          = $08  // <filename>
.label CTRL_CMD_SAVE_REU          = $09  // <filename>
.label CTRL_CMD_U64_SAVEMEM       = $0F  // <filename>, U64 family only
.label CTRL_CMD_DECODE_TRACK      = $11  // GCR -> binary in REU
.label CTRL_CMD_ENCODE_TRACK      = $12  // INFERRED: firmware only, not in the published spec
.label CTRL_CMD_EASYFLASH         = $20  // $00 <bank> <baseaddr> - sector erase
.label CTRL_CMD_GET_HWINFO        = $28  // [sub] $00 = model name, $01 = SID config
.label CTRL_CMD_GET_DRVINFO       = $29  // <effective_addr_flag>
.label CTRL_CMD_ENABLE_DRIVE_A    = $30
.label CTRL_CMD_DISABLE_DRIVE_A   = $31
.label CTRL_CMD_ENABLE_DRIVE_B    = $32
.label CTRL_CMD_DISABLE_DRIVE_B   = $33
.label CTRL_CMD_GET_DRIVE_A_POWER = $34
.label CTRL_CMD_GET_DRIVE_B_POWER = $35
.label CTRL_CMD_GET_RAMDISKINFO   = $40  // GEOS MegaPatch 3 RAM disk layout
.label CTRL_CMD_LOAD_CONFIG       = $50  // INFERRED: firmware only, not in the published spec
.label CTRL_CMD_GET_PALETTE       = $51  // -> 48 RGB bytes (FW > 3.15)
.label CTRL_CMD_SET_PALETTE       = $52  // <48 RGB bytes> (FW > 3.15)
.label CTRL_CMD_SET_PALETTE_COLOR = $53  // <index> <r> <g> <b> (FW > 3.15)
.label CTRL_CMD_RESET_PALETTE     = $54  // restore the built-in palette (FW > 3.15)

// ---- Control: VIC-II palette ----
// Runtime palette control. Affects the live palette only; it does not
// touch flash configuration or VPL files.
.label UCI_PALETTE_COLORS         = $10  // colors in a VIC-II palette
.label UCI_PALETTE_BYTES          = $30  // bytes in a full palette frame (16 * RGB)

// ---- Control: hardware info sub-commands ----
.label CTRL_HWINFO_MODEL          = $00  // ASCII model name, e.g. 'ULTIMATE 64'
.label CTRL_HWINFO_SID            = $01  // SID configuration frames

// ---- Control: drive type codes ----
// From CTRL_CMD_GET_DRVINFO.
.label CTRL_DRVTYPE_1541          = $00
.label CTRL_DRVTYPE_1571          = $01
.label CTRL_DRVTYPE_1581          = $02
.label CTRL_DRVTYPE_UNDECIDED     = $03
.label CTRL_DRVTYPE_SOFTIEC       = $0F
.label CTRL_DRVTYPE_PRINTER       = $50

// ---- SoftwareIEC commands (target $05) ----
.label SOFTIEC_CMD_IDENTIFY       = $01
.label SOFTIEC_CMD_LOAD_SU        = $10  // <sec> <verify> <addr16> <name>
.label SOFTIEC_CMD_LOAD_EX        = $11  // <sec> <verify>
.label SOFTIEC_CMD_SAVE           = $12  // <verify> <sec> <start16> <end16> <name>
.label SOFTIEC_CMD_OPEN           = $13  // <sec> $00 <name>
.label SOFTIEC_CMD_CLOSE          = $14  // <sec>
.label SOFTIEC_CMD_CHKIN          = $15  // <sec>
.label SOFTIEC_CMD_CHKOUT         = $16  // <sec> $00 <data...>
.label SOFTIEC_CMD_ADD_PARTITION  = $20  // <index> <ident>':'<path>
.label SOFTIEC_CMD_DEL_PARTITION  = $21  // <index>
.label SOFTIEC_CMD_GET_FATNAME    = $22  // <channel> <iec name>
.label SOFTIEC_CMD_GET_IECNAME    = $23  // <fat name>

// ---- SoftwareIEC status bytes ----
// This target returns a single binary status byte, not an ASCII status
// string.
.label SOFTIEC_ST_OK              = $00
.label SOFTIEC_ST_FILE_NOT_FOUND  = $01
.label SOFTIEC_ST_SAVE_ERROR      = $02
.label SOFTIEC_ST_NO_INPUT_CHANNEL = $03
.label SOFTIEC_ST_UNKNOWN_COMMAND = $04
.label SOFTIEC_ST_MODULE_NOT_LOADED = $05
.label SOFTIEC_ST_INVALID_PARAMS  = $06
.label SOFTIEC_ST_INVALID_NAME    = $07
.label SOFTIEC_ST_INVALID_PARTITION = $08
.label SOFTIEC_ST_INVALID_DIRECTORY = $09
.label SOFTIEC_ST_VERIFY_ERROR    = $80  // LOAD_EX verify mismatch

// ---- HTTP commands (target $06, FW 3.15+) ----
.label HTTP_CMD_IDENTIFY          = $01
.label HTTP_CMD_FREE_ALL          = $10
.label HTTP_CMD_HEADER_CREATE     = $11  // <verb> <url>
.label HTTP_CMD_HEADER_FREE       = $12  // <handle>
.label HTTP_CMD_HEADER_ADD        = $13  // <handle> <'key: value'>
.label HTTP_CMD_HEADER_QUERY      = $14  // <handle> <key>
.label HTTP_CMD_HEADER_LIST       = $15  // <handle> <index>
.label HTTP_CMD_BODY_CREATE       = $21  // <format>
.label HTTP_CMD_BODY_FREE         = $22  // <handle>
.label HTTP_CMD_BODY_ADD_INT      = $23  // <handle> <keylen> <key> <int>
.label HTTP_CMD_BODY_ADD_BOOL     = $24  // <handle> <keylen> <key> <bool>
.label HTTP_CMD_BODY_ADD_STRING   = $25  // <handle> <keylen> <key> <vallen> <val>
.label HTTP_CMD_BODY_ADD_OBJECT   = $26  // <handle> <keylen> <key>
.label HTTP_CMD_BODY_ADD_ARRAY    = $27  // <handle> <keylen> <key>
.label HTTP_CMD_BODY_UP           = $28  // <handle>
.label HTTP_CMD_BODY_REMOVE       = $29  // <handle> <path>
.label HTTP_CMD_BODY_QUERY        = $2A  // <handle> <path>
.label HTTP_CMD_BODY_MOVE         = $2B  // <handle> <path>
.label HTTP_CMD_BODY_ADD_BINARY   = $2C  // <handle> <data...>
.label HTTP_CMD_BODY_ADD          = $2D  // <handle> <items...>
.label HTTP_CMD_BODY_CLEAR        = $2E  // <handle>
.label HTTP_CMD_DO_EXCHANGE_OBJ   = $31  // <header> <body|$FF>
.label HTTP_CMD_DO_EXCHANGE_RAW   = $32  // <header> <body|$FF>

// ---- HTTP verbs ----
.label HTTP_VERB_GET              = $01
.label HTTP_VERB_PUT              = $02
.label HTTP_VERB_POST             = $03
.label HTTP_VERB_PATCH            = $04
.label HTTP_VERB_DELETE           = $05
.label HTTP_VERB_HEAD             = $06
.label HTTP_VERB_OPTIONS          = $07
.label HTTP_VERB_CONNECT          = $08
.label HTTP_VERB_TRACE            = $09

// ---- HTTP body formats ----
.label HTTP_BODY_BINARY           = $01
.label HTTP_BODY_JSON_OBJECT      = $02
.label HTTP_BODY_JSON_ARRAY       = $03
.label HTTP_BODY_URL_ENCODED      = $04
.label HTTP_BODY_NONE             = $FF  // Pass as <body> to send no body

// ---- HTTP / JSON value type tags ----
// Used by BODY_ADD and BODY_QUERY.
.label HTTP_TYPE_INT              = $01  // 4 bytes, LSB first
.label HTTP_TYPE_BOOL             = $02  // 1 byte
.label HTTP_TYPE_STRING           = $03  // <len> <bytes>
.label HTTP_TYPE_OBJECT           = $04  // <count> [<key> <value>]*
.label HTTP_TYPE_ARRAY            = $05  // <count> [<value>]*

// ---- SDK status / error codes ----
// Stable across firmware versions. The raw device status is preserved
// separately, see uci_last_device_code().
.label ULTIMATE_OK                = $00  // Success (device may still have set a warning code)
.label ULTIMATE_ERR_NO_DEVICE     = $01  // No Ultimate Command Interface found
.label ULTIMATE_ERR_TIMEOUT       = $02  // The Ultimate did not answer in time
.label ULTIMATE_ERR_PROTOCOL      = $03  // Transport-level protocol violation
.label ULTIMATE_ERR_NOT_SUPPORTED = $04  // Target or command not implemented by this firmware
.label ULTIMATE_ERR_INVALID_ARGUMENT = $05  // Bad argument supplied by the caller
.label ULTIMATE_ERR_IO            = $06  // File system / network I/O failure
.label ULTIMATE_ERR_DEVICE        = $07  // Target reported a failure status
.label ULTIMATE_ERR_TRUNCATED     = $08  // Reply did not fit in the caller's buffer
.label ULTIMATE_ERR_ABORTED       = $09  // Command was aborted

// ---- Request block layout ----
// Byte offsets into a uci_request. The assembly core is the authority on
// this layout; bindings/cc65/abi_assert.c fails the build if the C struct
// ever stops matching.
.label UCI_REQ_TARGET             = $00  // byte: target id, optionally | UCI_TARGET_NO_REPLY
.label UCI_REQ_COMMAND            = $01  // byte: command code
.label UCI_REQ_ARGS               = $02  // word: pointer to argument bytes, 0 for none
.label UCI_REQ_ARGLEN             = $04  // word: number of argument bytes
.label UCI_REQ_PAYLOAD            = $06  // word: pointer to payload bytes, 0 for none
.label UCI_REQ_PAYLOADLEN         = $08  // word: number of payload bytes
.label UCI_REQ_DATA               = $0A  // word: buffer for the reply, 0 to discard it
.label UCI_REQ_DATAMAX            = $0C  // word: size of that buffer
.label UCI_REQ_DATALEN            = $0E  // word: out, reply bytes stored
.label UCI_REQ_STATUS             = $10  // word: buffer for the status string, 0 to discard
.label UCI_REQ_STATUSMAX          = $12  // word: size of that buffer
.label UCI_REQ_STATUSLEN          = $14  // word: out, status bytes stored
.label UCI_REQ_SIZE               = $16  // total size of the block

// ---- SDK memory footprint ----
// How much RAM the core needs, and where. All of it is placeable: see
// UCI_ZP and UCI_VARS in docs/asm-abi.md.
.label UCI_ZP_SIZE                = $04  // zero page bytes the core needs
.label UCI_VARS_SIZE              = $58  // non-zero-page bytes the whole SDK needs

// ---- ASCII literals ----
// Bytes that come off the wire are always written numerically. An
// assembler charmap, or a compiler's idea of the target character set,
// must never reach them: cc65 turns "NO TARGET" into PETSCII, which
// silently stops matching what the Ultimate sends.
.label UCI_ASCII_ZERO             = $30  // '0'
.label UCI_ASCII_NINE             = $39  // '9'
.label UCI_ASCII_COMMA            = $2C  // ','
.label UCI_ASCII_SPACE            = $20  // ' '

// ---- Status string families ----
// Targets do not agree on how status is encoded; the SDK picks a decoder
// per target.
.label UCI_STATUS_FMT_DECIMAL2    = $00  // 'NN,TEXT' - DOS, Network, Control
.label UCI_STATUS_FMT_DECIMAL3    = $01  // 'NNN TEXT' - HTTP
.label UCI_STATUS_FMT_BINARY      = $02  // single binary byte - SoftwareIEC
.label UCI_STATUS_FMT_NONE        = $03  // target sends no status
