// Generated by tools/gen_protocol.py - DO NOT EDIT BY HAND.
//
// Ultimate Command Interface constants for KickAssembler.
//
//     #import "uci_protocol.asm"
//     lda #uci.UCI_TARGET_DOS1
//
// The code itself is not linkable from KickAssembler; use the
// standalone binary in bindings/blob, which needs no linking at all.
//
// SPDX-License-Identifier: MIT

.filenamespace uci

// ---- Register map ----
// UCI I/O registers. The block is mapped at $DF1B-$DF1F and overlays the
// last five REU registers. Mapping is optional and is enabled in the
// Ultimate 'Command Interface' configuration menu.
.label UCI_REG_BUSID              = $DF1B  // R   SoftwareIEC bus ID (0 = unset)
.label UCI_REG_CONTROL            = $DF1C  // W   Control register
.label UCI_REG_STATUS             = $DF1C  // R   Status register
.label UCI_REG_CMDDATA            = $DF1D  // W   Command data (write command bytes here)
.label UCI_REG_IDENT              = $DF1D  // R   Identification register
.label UCI_REG_RESPDATA           = $DF1E  // R   Response data queue
.label UCI_REG_STATDATA           = $DF1F  // R   Status data queue

// ---- Identification register values ----
// Read from UCI_REG_IDENT.
.label UCI_IDENT_IDLE             = $C9  // No interrupt pending
.label UCI_IDENT_IRQ              = $49  // Interrupt active (bit 7 cleared). FW 3.15+
.label UCI_IDENT_MASK             = $7F  // Mask off the IRQ bit before comparing
.label UCI_IDENT_VALUE            = $49  // Expected value after masking with UCI_IDENT_MASK

// ---- Control register bits ----
// Write-only. Always write a literal mask; never read-modify-write,
// because reading $DF1C returns the status register, not the control
// register.
.label UCI_CTRL_PUSH_CMD          = $01  // Submit the buffered command
.label UCI_CTRL_DATA_ACC          = $02  // Acknowledge / release the current data block
.label UCI_CTRL_ABORT             = $04  // Request abort of the running command
.label UCI_CTRL_CLR_ERR           = $08  // Clear the state-error flag
.label UCI_CTRL_IRQ               = $20  // Raise IRQ on completion (FW 3.15+, latched on push)
.label UCI_CTRL_TRIGGER           = $40  // Freeze the machine on the next $FF00 write (latched on push). NOT a transfer accelerator
.label UCI_CTRL_DMA               = $80  // Freeze the machine immediately (latched on push). NOT a transfer accelerator - see docs/uci.md

// ---- Status register bits ----
// Read from $DF1C.
.label UCI_STAT_CMD_BUSY          = $01  // A command is pending in command memory
.label UCI_STAT_DATA_ACC          = $02  // Data acknowledge seen by the Ultimate
.label UCI_STAT_ABORT_P           = $04  // Abort request still pending
.label UCI_STAT_ERROR             = $08  // State error: command pushed while not idle
.label UCI_STAT_STATE             = $30  // Protocol state mask
.label UCI_STAT_STAT_AV           = $40  // Status byte available at $DF1F
.label UCI_STAT_DATA_AV           = $80  // Response byte available at $DF1E

// ---- Protocol states ----
// Value of (status & UCI_STAT_STATE).
.label UCI_STATE_IDLE             = $00  // Ready to accept a command
.label UCI_STATE_BUSY             = $10  // Command submitted, Ultimate is working
.label UCI_STATE_DATA_LAST        = $20  // Data available, this is the final block
.label UCI_STATE_DATA_MORE        = $30  // Data available, more blocks follow

// ---- Queue sizes ----
// Hard limits enforced by the hardware. The three queue pointers all
// saturate on the LAST byte of their buffer rather than one past it, which
// costs a byte on the way in and can hang a naive reader on the way out -
// see docs/uci.md, 'Queue pointer saturation'.
.label UCI_MAX_COMMAND            = $0380  // Command queue size in bytes ($380)
.label UCI_MAX_RESPONSE           = $0380  // Response data queue size in bytes ($380)
.label UCI_MAX_STATUS             = $0100  // Status queue size in bytes ($100)
.label UCI_MAX_COMMAND_USABLE     = $037F  // Largest command the hardware can actually receive

// ---- Timeouts ----
// Budget for a status poll loop, in units of 256 polls. The core installs
// the default at bring-up, so the bounded-time guarantee holds without the
// caller doing anything; raise it around a command whose duration cannot
// be bounded and restore it after.
.label UCI_TIMEOUT_DEFAULT        = $C8  // Comfortable for local commands at any CPU speed
.label UCI_TIMEOUT_FOREVER        = $00  // Poll until the Ultimate answers, however long that takes

// ---- Targets ----
// First byte of every command. Only bits 0-3 select the target; bit 7 is
// the NO_REPLY flag (INFERRED from firmware).
.label UCI_TARGET_MASK            = $0F  // Target field of the first command byte
.label UCI_TARGET_NO_REPLY        = $80  // Fire-and-forget: skip the data/status phase
.label UCI_TARGET_DOS1            = $01  // Ultimate DOS instance 1
.label UCI_TARGET_DOS2            = $02  // Ultimate DOS instance 2
.label UCI_TARGET_NETWORK         = $03  // Network (TCP/UDP sockets)
.label UCI_TARGET_CONTROL         = $04  // Machine / cartridge control
.label UCI_TARGET_SOFTIEC         = $05  // SoftwareIEC bypass
.label UCI_TARGET_HTTP            = $06  // HTTP client (FW 3.15+)
.label UCI_TARGET_MAX             = $0F  // Highest addressable target

// ---- Commands common to every target ----
.label UCI_CMD_IDENTIFY           = $01  // Return an identification string. Cannot fail.

// ---- Ultimate DOS commands (targets $01/$02) ----
.label DOS_CMD_IDENTIFY           = $01
.label DOS_CMD_OPEN_FILE          = $02  // <attrib> <filename> - attrib is a DOS_FA_* mask
.label DOS_CMD_CLOSE_FILE         = $03
.label DOS_CMD_READ_DATA          = $04  // <len:16> - arrives as 512-byte blocks; uci_exec walks the chain
.label DOS_CMD_WRITE_DATA         = $05  // $00 $00 <data...> - the two fixed bytes are skipped, not stored
.label DOS_CMD_FILE_SEEK          = $06  // <pos:32>
.label DOS_CMD_FILE_INFO          = $07
.label DOS_CMD_FILE_STAT          = $08  // <filename>
.label DOS_CMD_DELETE_FILE        = $09  // <filename>
.label DOS_CMD_RENAME_FILE        = $0A  // <old> $00 <new>
.label DOS_CMD_COPY_FILE          = $0B  // <src> $00 <dst>
.label DOS_CMD_CHANGE_DIR         = $11  // <dirname>
.label DOS_CMD_GET_PATH           = $12
.label DOS_CMD_OPEN_DIR           = $13
.label DOS_CMD_READ_DIR           = $14
.label DOS_CMD_COPY_UI_PATH       = $15  // Deprecated since FW 3.0
.label DOS_CMD_CREATE_DIR         = $16  // <dirname>
.label DOS_CMD_COPY_HOME_PATH     = $17
.label DOS_CMD_LOAD_REU           = $21  // <addr:32> <len:32> - the safe REU pair; never wrap the control pair, see #740
.label DOS_CMD_SAVE_REU           = $22  // <addr:32> <len:32> - the safe REU pair; never wrap the control pair, see #740
.label DOS_CMD_MOUNT_DISK         = $23  // <id> <filename>
.label DOS_CMD_UMOUNT_DISK        = $24  // <id>
.label DOS_CMD_SWAP_DISK          = $25  // <id>
.label DOS_CMD_GET_TIME           = $26  // <fmt> - fmt may be omitted; the target defaults it to $00
.label DOS_CMD_SET_TIME           = $27  // <year_1900> <month> <day> <hour> <minute> <second> - year is the year minus 1900
.label DOS_CMD_LOAD_RAMDISK       = $41  // <drive> <filename> - GEOS MegaPatch RAM disk; the firmware header spells it CTRL_CMD_LOAD_INTO_RAMDISK and puts it on this target
.label DOS_CMD_SAVE_RAMDISK       = $42  // <drive> <filename> - GEOS MegaPatch RAM disk; the firmware header spells it CTRL_CMD_SAVE_RAMDISK and puts it on this target
.label DOS_CMD_ECHO               = $F0  // <data...> - Echo the command back as data

// ---- DOS file open attributes ----
// Bit flags for DOS_CMD_OPEN_FILE.
.label DOS_FA_READ                = $01  // Open for reading
.label DOS_FA_WRITE               = $02  // Open for writing, do not truncate
.label DOS_FA_CREATE_NEW          = $04  // Create/truncate to zero bytes
.label DOS_FA_CREATE_ALWAYS       = $08  // May overwrite an existing file

// ---- DOS file information reply ----
// Byte offsets into the reply of DOS_CMD_FILE_STAT and DOS_CMD_FILE_INFO.
// The name is last, has no terminator, and its length is the reply length
// less DOS_INFO_NAME. Read from t_dos_info in software/filemanager/dos.h.
.label DOS_INFO_SIZE              = $00  // file size, 32-bit little-endian
.label DOS_INFO_DATE              = $04  // FAT date, 16-bit little-endian
.label DOS_INFO_TIME              = $06  // FAT time, 16-bit little-endian
.label DOS_INFO_EXTENSION         = $08  // three bytes, space padded, not terminated
.label DOS_INFO_ATTRIB            = $0B  // DOS_ATTR_* bits
.label DOS_INFO_NAME              = $0C  // the name begins here
.label DOS_INFO_NAME_MAX          = $3F  // longest name the firmware copies

// ---- DOS directory entry attributes ----
// First byte of each DOS_CMD_READ_DIR entry (FAT semantics).
.label DOS_ATTR_READONLY          = $01
.label DOS_ATTR_HIDDEN            = $02
.label DOS_ATTR_SYSTEM            = $04
.label DOS_ATTR_VOLUME            = $08
.label DOS_ATTR_DIR               = $10
.label DOS_ATTR_ARCHIVE           = $20

// ---- Network commands (target $03) ----
.label NET_CMD_IDENTIFY           = $01
.label NET_CMD_GET_INTERFACE_COUNT = $02
.label NET_CMD_SET_INTERFACE      = $03  // RESERVED: the firmware's case is commented out, so this answers 21,UNKNOWN COMMAND
.label NET_CMD_GET_NETADDR        = $04  // <iface> - replies with UCI_NET_MACADDR_BYTES
.label NET_CMD_GET_IPADDR         = $05  // <iface> - replies with UCI_NET_IPCONFIG_BYTES, ip/mask/gw
.label NET_CMD_SET_IPADDR         = $06  // <iface> <ipconfig...> - ipconfig must be exactly UCI_NET_IPCONFIG_BYTES
.label NET_CMD_OPEN_TCP           = $07  // <port:16> <host>
.label NET_CMD_OPEN_UDP           = $08  // <port:16> <host>
.label NET_CMD_CLOSE_SOCKET       = $09  // <handle>
.label NET_CMD_READ_SOCKET        = $10  // <handle> <len:16>
.label NET_CMD_WRITE_SOCKET       = $11  // <handle> <data...>
.label NET_CMD_LISTEN_START       = $12  // <port:16> - INFERRED: not in the published spec
.label NET_CMD_LISTEN_STOP        = $13  // INFERRED: not in the published spec
.label NET_CMD_LISTEN_STATE       = $14  // INFERRED: not in the published spec
.label NET_CMD_LISTEN_SOCKET      = $15  // INFERRED: not in the published spec

// ---- Network address sizes ----
// Fixed-width blobs the network target exchanges.
.label UCI_NET_MACADDR_BYTES      = $06  // bytes in a MAC address
.label UCI_NET_IPCONFIG_BYTES     = $0C  // bytes in an ip/mask/gateway triple
.label UCI_NET_READ_PREFIX        = $02  // 16-bit count the firmware puts in front of socket data
.label UCI_NET_READ_MAX           = $0200  // largest READ_SOCKET this SDK will ask for - see docs/uci.md
.label UCI_NET_NO_DATA            = $FFFF  // that count, when nothing was available to read
.label UCI_NET_DEV_OK             = $00  // network device code: the reply carries data
.label UCI_NET_DEV_CLOSED         = $01  // network device code: the peer hung up, reported once
.label UCI_NET_DEV_NO_DATA        = $02  // network device code: nothing pending, try again

// ---- Control commands (target $04) ----
.label CTRL_CMD_IDENTIFY          = $01
.label CTRL_CMD_READ_RTC          = $02  // INFERRED: firmware only, not in the published spec
.label CTRL_CMD_FINISH_CAPTURE    = $03
.label CTRL_CMD_FREEZE            = $05
.label CTRL_CMD_REBOOT            = $06  // Never replies: the C64 and the UCI are reset
.label CTRL_CMD_LOAD_REU          = $08  // <filename> - never returns on FW 3.14d and wedges the interface, see #740
.label CTRL_CMD_SAVE_REU          = $09  // <filename>
.label CTRL_CMD_U64_SAVEMEM       = $0F  // <filename> - U64 family only
.label CTRL_CMD_DECODE_TRACK      = $11  // GCR -> binary in REU
.label CTRL_CMD_ENCODE_TRACK      = $12  // INFERRED: firmware only, not in the published spec
.label CTRL_CMD_EASYFLASH         = $20  // $00 <bank> <baseaddr> - sector erase; baseaddr bit $20 selects the high ROM
.label CTRL_CMD_GET_HWINFO        = $28  // <sub> - deprecated; sub may be omitted; defaults to CTRL_HWINFO_MODEL
.label CTRL_CMD_GET_DRVINFO       = $29  // <effective_addr>
.label CTRL_CMD_ENABLE_DRIVE_A    = $30
.label CTRL_CMD_DISABLE_DRIVE_A   = $31
.label CTRL_CMD_ENABLE_DRIVE_B    = $32
.label CTRL_CMD_DISABLE_DRIVE_B   = $33
.label CTRL_CMD_GET_DRIVE_A_POWER = $34
.label CTRL_CMD_GET_DRIVE_B_POWER = $35
.label CTRL_CMD_GET_RAMDISKINFO   = $40  // GEOS MegaPatch 3 RAM disk layout
.label CTRL_CMD_LOAD_CONFIG       = $50  // INFERRED: firmware only, not in the published spec
.label CTRL_CMD_GET_PALETTE       = $51  // -> 48 RGB bytes (FW > 3.15)
.label CTRL_CMD_SET_PALETTE       = $52  // <palette...> - palette is exactly UCI_PALETTE_BYTES (FW > 3.15)
.label CTRL_CMD_SET_PALETTE_COLOR = $53  // <index> <r> <g> <b> - (FW > 3.15)
.label CTRL_CMD_RESET_PALETTE     = $54  // restore the built-in palette (FW > 3.15)

// ---- Control: VIC-II palette ----
// Runtime palette control. Affects the live palette only; it does not
// touch flash configuration or VPL files.
.label UCI_PALETTE_COLORS         = $10  // colors in a VIC-II palette
.label UCI_PALETTE_BYTES          = $30  // bytes in a full palette frame (16 * RGB)

// ---- Control: deprecated hardware info sub-commands ----
.label CTRL_HWINFO_MODEL          = $00  // ASCII model name, e.g. 'ULTIMATE 64'
.label CTRL_HWINFO_SID            = $01  // deprecated SID configuration frames

// ---- Control: drive type codes ----
// From CTRL_CMD_GET_DRVINFO.
.label CTRL_DRVTYPE_1541          = $00
.label CTRL_DRVTYPE_1571          = $01
.label CTRL_DRVTYPE_1581          = $02
.label CTRL_DRVTYPE_UNDECIDED     = $03
.label CTRL_DRVTYPE_SOFTIEC       = $0F
.label CTRL_DRVTYPE_PRINTER       = $50

// ---- Control: the physical drives ----
// Drives A and B. CTRL_CMD_ENABLE_DRIVE_A through
// CTRL_CMD_GET_DRIVE_B_POWER are one command per drive, so this is how
// many drives those commands can name. It is not how many records
// CTRL_CMD_GET_DRVINFO can return - see CTRL_DRVINFO_MAX.
.label CTRL_DRIVE_SLOTS           = $02  // drives the enable and power commands address

// ---- Control: drive information reply ----
// Layout of the CTRL_CMD_GET_DRVINFO reply: a count, then one record per
// drive the machine has. control_target.cc emits drives A and B, then
// IecInterface::info in iec_interface.cc adds one record per occupied IEC
// bus slot.
.label CTRL_DRVINFO_COUNT         = $00  // offset of the drive count
.label CTRL_DRVINFO_FIRST         = $01  // offset of the first record
.label CTRL_DRVINFO_RECORD        = $03  // bytes per record: type, IEC address, power
.label CTRL_DRVINFO_SLAVES        = $04  // IEC bus slots, MAX_SLOTS in iec_interface.h
.label CTRL_DRVINFO_MAX           = $06  // records the count can reach: two drives and four slots
.label CTRL_DRVINFO_BYTES         = $13  // longest reply: the count and six records

// ---- Control: RAM disk information reply ----
// Layout of the CTRL_CMD_GET_RAMDISKINFO reply: four two-byte records,
// each a drive type code and the size in 64K units.
.label CTRL_RAMDISK_DRIVES        = $04  // records in the reply
.label CTRL_RAMDISK_BYTES         = $08  // bytes in the reply

// ---- Control: drive power reply ----
// CTRL_CMD_GET_DRIVE_A_POWER and its B counterpart answer with three ASCII
// bytes rather than a flag.
.label CTRL_POWER_BYTES           = $03  // bytes in the reply: 'on ' or 'off'

// ---- SoftwareIEC commands (target $05) ----
.label SOFTIEC_CMD_IDENTIFY       = $01  // answers in ASCII; every other command on this target answers in binary
.label SOFTIEC_CMD_LOAD_SU        = $10  // <sec> <verify> <addr:16> <unused:16> <name> - sec 1 uses the file's own load address, 0 uses addr; unused is never read but must be sent
.label SOFTIEC_CMD_LOAD_EX        = $11  // <sec> <verify> - returns the end address in status bytes 1-2
.label SOFTIEC_CMD_SAVE           = $12  // <verify> <sec> <start:16> <end:16> <name>
.label SOFTIEC_CMD_OPEN           = $13  // <sec> $00 <name>
.label SOFTIEC_CMD_CLOSE          = $14  // <sec>
.label SOFTIEC_CMD_CHKIN          = $15  // <sec>
.label SOFTIEC_CMD_CHKOUT         = $16  // <sec> $00 <data...> - sec & $F0 of $F0 opens and $E0 closes; anything else pushes data
.label SOFTIEC_CMD_ADD_PARTITION  = $20  // <index> <ident_colon_path> - the string is 'IDENT:/path'
.label SOFTIEC_CMD_DEL_PARTITION  = $21  // <index>
.label SOFTIEC_CMD_GET_FATNAME    = $22  // <channel> <iec_name> - resolves an IEC name to a host path
.label SOFTIEC_CMD_GET_IECNAME    = $23  // <fat_name>

// ---- SoftwareIEC status bytes ----
// This target returns a single binary status byte, not an ASCII status
// string.
.label SOFTIEC_ST_OK              = $00
.label SOFTIEC_ST_FILE_NOT_FOUND  = $01
.label SOFTIEC_ST_SAVE_ERROR      = $02
.label SOFTIEC_ST_NO_INPUT_CHANNEL = $03
.label SOFTIEC_ST_UNKNOWN_COMMAND = $04
.label SOFTIEC_ST_MODULE_NOT_LOADED = $05
.label SOFTIEC_ST_INVALID_PARAMS  = $06
.label SOFTIEC_ST_INVALID_NAME    = $07
.label SOFTIEC_ST_INVALID_PARTITION = $08
.label SOFTIEC_ST_INVALID_DIRECTORY = $09
.label SOFTIEC_ST_VERIFY_ERROR    = $80  // LOAD_EX verify mismatch

// ---- HTTP commands (target $06, FW 3.15+) ----
.label HTTP_CMD_IDENTIFY          = $01
.label HTTP_CMD_FREE_ALL          = $10
.label HTTP_CMD_HEADER_CREATE     = $11  // <verb> <url> - verb is an HTTP_VERB_* code
.label HTTP_CMD_HEADER_FREE       = $12  // <handle>
.label HTTP_CMD_HEADER_ADD        = $13  // <handle> <key_colon_value> - the string is 'key: value'
.label HTTP_CMD_HEADER_QUERY      = $14  // <handle> <key>
.label HTTP_CMD_HEADER_LIST       = $15  // <handle> <index>
.label HTTP_CMD_BODY_CREATE       = $21  // <format> - format is an HTTP_BODY_* code
.label HTTP_CMD_BODY_FREE         = $22  // <handle>
.label HTTP_CMD_BODY_ADD_INT      = $23  // <handle> <key:len> <key> <value:32> - 1 to 4 value bytes are accepted, sign-extended from the last; send four
.label HTTP_CMD_BODY_ADD_BOOL     = $24  // <handle> <key:len> <key> <value> - any non-zero value is true
.label HTTP_CMD_BODY_ADD_STRING   = $25  // <handle> <key:len> <key> <value:len> <value>
.label HTTP_CMD_BODY_ADD_OBJECT   = $26  // <handle> <key:len> <key>
.label HTTP_CMD_BODY_ADD_ARRAY    = $27  // <handle> <key:len> <key>
.label HTTP_CMD_BODY_UP           = $28  // <handle>
.label HTTP_CMD_BODY_REMOVE       = $29  // <handle> <path>
.label HTTP_CMD_BODY_QUERY        = $2A  // <handle> <path>
.label HTTP_CMD_BODY_MOVE         = $2B  // <handle> <path>
.label HTTP_CMD_BODY_ADD_BINARY   = $2C  // <handle> <data...>
.label HTTP_CMD_BODY_ADD          = $2D  // <handle> <items...>
.label HTTP_CMD_BODY_CLEAR        = $2E  // <handle>
.label HTTP_CMD_DO_EXCHANGE_OBJ   = $31  // <header> <body> - pass HTTP_BODY_NONE as body to send none
.label HTTP_CMD_DO_EXCHANGE_RAW   = $32  // <header> <body> - pass HTTP_BODY_NONE as body to send none

// ---- HTTP verbs ----
.label HTTP_VERB_GET              = $01
.label HTTP_VERB_PUT              = $02
.label HTTP_VERB_POST             = $03
.label HTTP_VERB_PATCH            = $04
.label HTTP_VERB_DELETE           = $05
.label HTTP_VERB_HEAD             = $06
.label HTTP_VERB_OPTIONS          = $07
.label HTTP_VERB_CONNECT          = $08
.label HTTP_VERB_TRACE            = $09

// ---- HTTP body formats ----
.label HTTP_BODY_BINARY           = $01
.label HTTP_BODY_JSON_OBJECT      = $02
.label HTTP_BODY_JSON_ARRAY       = $03
.label HTTP_BODY_URL_ENCODED      = $04
.label HTTP_BODY_NONE             = $FF  // Pass as <body> to send no body

// ---- HTTP / JSON value type tags ----
// Used by BODY_ADD and BODY_QUERY.
.label HTTP_TYPE_INT              = $01  // 4 bytes, LSB first
.label HTTP_TYPE_BOOL             = $02  // 1 byte
.label HTTP_TYPE_STRING           = $03  // <len> <bytes>
.label HTTP_TYPE_OBJECT           = $04  // <count> [<key> <value>]*
.label HTTP_TYPE_ARRAY            = $05  // <count> [<value>]*

// ---- Ultimate 64 turbo control (NOT UCI) ----
// The one part of the machine the SDK reaches without the command
// interface, because there is no UCI command for CPU speed. Plain memory-
// mapped registers, documented at 1541u-documentation.readthedocs.io. They
// answer $FF unless the Ultimate's 'Turbo Control' setting is 'U64 Turbo
// Registers' or 'Turbo Enable Bit', which is what makes availability
// testable rather than assumed.
.label U64_REG_TURBO              = $D031  // R/W  bits 0-3 speed index, bit 7 badlines off
.label U64_REG_TURBO_ENABLE       = $D030  // R/W  bit 0, in 'Turbo Enable Bit' mode only
.label U64_TURBO_SPEED_MASK       = $0F  // speed index field of U64_REG_TURBO
.label U64_TURBO_NO_BADLINES      = $80  // set to stop the VIC stealing cycles
.label U64_TURBO_UNAVAILABLE      = $FF  // what both registers read when turbo is off in config

// ---- REU registers (NOT UCI) ----
// The second and last thing the SDK reaches without the command interface,
// for the same reason as turbo: no UCI command moves bytes between C64 RAM
// and the REU. The register set is the 1750's, implemented in
// fpga/cart_slot/vhdl_source/reu.vhd, and the command interface overlays
// $DF1B-$DF1F above it - the REU decodes $DF00-$DF17 only, so the two
// coexist. A transfer runs under DMA with the CPU halted, so it is
// finished by the time the next instruction runs.
.label REU_REG_STATUS             = $DF00  // R    bit 7 IRQ, 6 done, 5 verify error, 4 size; reading clears 6 and 5
.label REU_REG_COMMAND            = $DF01  // R/W  bit 7 execute, 5 autoload, 4 start now, bits 1-0 mode
.label REU_REG_C64_LO             = $DF02  // R/W  C64 base address, low
.label REU_REG_C64_HI             = $DF03  // R/W  C64 base address, high
.label REU_REG_ADDR_LO            = $DF04  // R/W  REU base address, low
.label REU_REG_ADDR_MID           = $DF05  // R/W  REU base address, middle
.label REU_REG_ADDR_HI            = $DF06  // R/W  REU base address, high
.label REU_REG_LEN_LO             = $DF07  // R/W  transfer length, low
.label REU_REG_LEN_HI             = $DF08  // R/W  transfer length, high; 0 means 65536
.label REU_REG_IRQMASK            = $DF09  // R/W  bit 7 enable, 6 on done, 5 on verify error
.label REU_REG_CONTROL            = $DF0A  // R/W  bit 7 fix C64 address, bit 6 fix REU address

// ---- REU command and status bits ----
// Written to REU_REG_COMMAND and read back from REU_REG_STATUS.
// REU_CMD_NOW is not optional for a program driving the REU itself: with
// it clear the transfer waits for a write to $FF00, which is the trick a
// cartridge uses and a nuisance everywhere else.
.label REU_CMD_EXECUTE            = $80  // start the transfer
.label REU_CMD_AUTOLOAD           = $20  // reload address and length after it finishes
.label REU_CMD_NOW                = $10  // start now rather than on a write to $FF00
.label REU_MODE_STASH             = $00  // C64 -> REU
.label REU_MODE_FETCH             = $01  // REU -> C64
.label REU_MODE_SWAP              = $02  // exchange both ways
.label REU_MODE_VERIFY            = $03  // compare without writing anything
.label REU_STAT_DONE              = $40  // the transfer finished; cleared by reading the register
.label REU_STAT_VERIFY_ERROR      = $20  // a verify found a difference
.label REU_STAT_SIZE              = $10  // set on 256K and larger

// ---- Ultimate Audio registers (NOT UCI) ----
// Seven hardware PCM voices mapped at $DF20-$DFFF when the machine's 'Map
// Ultimate Audio' setting is enabled. Multi-byte fields are written most-
// significant byte first. Sample addresses are offsets into the 16 MB REU
// window; the hardware adds the SDRAM base byte $01.
.label UA_REG_BASE                = $DF20  // channel 0 base; each channel occupies 32 bytes
.label UA_REG_IRQ_STATUS          = $DF20  // R    one end-of-sample bit per channel
.label UA_REG_VERSION             = $DF21  // R    module version; $10 is version 1.0
.label UA_CHANNEL_STRIDE          = $20  // bytes between channel register blocks
.label UA_CHANNELS                = $07  // software-visible channels 0-6
.label UA_VERSION_1_0             = $10  // known register API version
.label UA_REG_CONTROL             = $00  // W    gate, repeat, IRQ, format and interleave
.label UA_REG_VOLUME              = $01  // W    0-63
.label UA_REG_PAN                 = $02  // W    0 left, 7/8 centre, 15 right
.label UA_REG_START               = $04  // W    32-bit SDRAM address, big endian
.label UA_REG_LENGTH              = $09  // W    24-bit byte count, big endian
.label UA_REG_RATE                = $0E  // W    divider from 6.25 MHz, big endian
.label UA_RATE_CLOCK              = $5F5E10  // the sampler's reference in Hz; a voice's rate is UA_RATE_CLOCK / sample rate
.label UA_REG_REPEAT_A            = $11  // W    24-bit loop start offset, big endian
.label UA_REG_REPEAT_B            = $15  // W    24-bit loop end offset, big endian
.label UA_REG_IRQ_CLEAR           = $1F  // W    1 clears this channel; $FF clears all
.label UA_REU_SDRAM_BANK          = $01  // upper byte of an address in the REU window

// ---- Ultimate Audio control bits ----
// Written to a channel's UA_REG_CONTROL.
.label UA_CTRL_GATE               = $01  // start the channel
.label UA_CTRL_REPEAT             = $02  // loop between repeat points A and B
.label UA_CTRL_IRQ                = $04  // raise IRQ at the end of the sample
.label UA_CTRL_16BIT              = $10  // 16-bit little-endian PCM; clear for 8-bit PCM
.label UA_CTRL_INTERLEAVE         = $40  // skip the other channel in interleaved stereo data
.label UA_CTRL_FLAGS              = $56  // all caller-selectable bits, excluding gate
.label UA_VOLUME_MAX              = $3F  // largest valid per-channel volume
.label UA_PAN_LEFT                = $00  // hard left
.label UA_PAN_CENTER              = $07  // centre (8 is also centred)
.label UA_PAN_RIGHT               = $0F  // hard right

// ---- Ultimate Audio voice layout ----
// Byte offsets in ultimate_audio_voice. The C ABI build asserts the
// structure still matches these.
.label UA_VOICE_CHANNEL           = $00  // byte
.label UA_VOICE_FLAGS             = $01  // byte
.label UA_VOICE_VOLUME            = $02  // byte
.label UA_VOICE_PAN               = $03  // byte
.label UA_VOICE_REU               = $04  // dword, little endian
.label UA_VOICE_LENGTH            = $08  // dword, little endian
.label UA_VOICE_REPEAT_A          = $0C  // dword, little endian
.label UA_VOICE_REPEAT_B          = $10  // dword, little endian
.label UA_VOICE_RATE              = $14  // word, little endian
.label UA_VOICE_SIZE              = $16  // bytes

// ---- Ultimate 64 speed indices ----
// Index into the machine's speed table. **Only these four mean the same
// thing on both machines.** The U64 runs 1,2,3,4,5,6,8..48 MHz and the
// U64-II runs 1,2,3,4,6,8..64, so index 4 is 5 MHz on one and 6 MHz on the
// other. Above 4 MHz, ask for an index and you get whatever that machine's
// table says.
.label U64_SPEED_1MHZ             = $00  // stock C64 speed, and what turbo_off restores
.label U64_SPEED_2MHZ             = $01
.label U64_SPEED_3MHZ             = $02
.label U64_SPEED_4MHZ             = $03  // the fastest index that means the same on both
.label U64_SPEED_MAX              = $0F  // whatever the machine's top speed is: 48 or 64 MHz

// ---- SDK status / error codes ----
// Stable across firmware versions. The raw device status is preserved
// separately, see uci_last_device_code().
.label ULTIMATE_OK                = $00  // Success (device may still have set a warning code)
.label ULTIMATE_ERR_NO_DEVICE     = $01  // No Ultimate Command Interface found
.label ULTIMATE_ERR_TIMEOUT       = $02  // The Ultimate did not answer in time
.label ULTIMATE_ERR_PROTOCOL      = $03  // Transport-level protocol violation
.label ULTIMATE_ERR_NOT_SUPPORTED = $04  // Target or command not implemented by this firmware
.label ULTIMATE_ERR_INVALID_ARGUMENT = $05  // Bad argument supplied by the caller
.label ULTIMATE_ERR_IO            = $06  // File system / network I/O failure
.label ULTIMATE_ERR_DEVICE        = $07  // Target reported a failure status
.label ULTIMATE_ERR_TRUNCATED     = $08  // Reply did not fit in the caller's buffer
.label ULTIMATE_ERR_ABORTED       = $09  // Command was aborted
.label ULTIMATE_END               = $0A  // No more entries: the end of a directory, not a failure
.label ULTIMATE_ERR_COUNT         = $0B  // Number of codes above, for a table that maps them

// ---- Request block layout ----
// Byte offsets into a uci_request. The assembly core is the authority on
// this layout; bindings/cc65/abi_assert.c fails the build if the C struct
// ever stops matching.
.label UCI_REQ_TARGET             = $00  // byte: target id, optionally | UCI_TARGET_NO_REPLY
.label UCI_REQ_COMMAND            = $01  // byte: command code
.label UCI_REQ_ARGS               = $02  // word: pointer to argument bytes, 0 for none
.label UCI_REQ_ARGLEN             = $04  // word: number of argument bytes
.label UCI_REQ_PAYLOAD            = $06  // word: pointer to payload bytes, 0 for none
.label UCI_REQ_PAYLOADLEN         = $08  // word: number of payload bytes
.label UCI_REQ_DATA               = $0A  // word: buffer for the reply, 0 to discard it
.label UCI_REQ_DATAMAX            = $0C  // word: size of that buffer
.label UCI_REQ_DATALEN            = $0E  // word: out, reply bytes stored
.label UCI_REQ_STATUS             = $10  // word: buffer for the status string, 0 to discard
.label UCI_REQ_STATUSMAX          = $12  // word: size of that buffer
.label UCI_REQ_STATUSLEN          = $14  // word: out, status bytes stored
.label UCI_REQ_SIZE               = $16  // total size of the block

// ---- SDK memory footprint ----
// How much RAM the core needs, and where. All of it is placeable: see
// UCI_ZP and UCI_VARS in docs/asm-abi.md.
.label UCI_ZP_SIZE                = $04  // zero page bytes the core needs
.label UCI_VARS_SIZE              = $BF  // non-zero-page bytes the whole SDK needs

// ---- ASCII literals ----
// Bytes that come off the wire are always written numerically. An
// assembler charmap, or a compiler's idea of the target character set,
// must never reach them: cc65 turns "NO TARGET" into PETSCII, which
// silently stops matching what the Ultimate sends.
.label UCI_ASCII_ZERO             = $30  // '0'
.label UCI_ASCII_NINE             = $39  // '9'
.label UCI_ASCII_COMMA            = $2C  // ','
.label UCI_ASCII_SPACE            = $20  // ' '

// ---- Status string families ----
// Targets do not agree on how status is encoded; the SDK picks a decoder
// per target.
.label UCI_STATUS_FMT_DECIMAL2    = $00  // 'NN,TEXT' - DOS, Network, Control
.label UCI_STATUS_FMT_DECIMAL3    = $01  // 'NNN TEXT' - HTTP
.label UCI_STATUS_FMT_BINARY      = $02  // single binary byte - SoftwareIEC
.label UCI_STATUS_FMT_NONE        = $03  // target sends no status

// ---- Blob jump table ----
// Offsets from the base address of the standalone blob (bindings/blob),
// whatever base it was built for: jsr BLOB + BLOB_ULTIMATE_INIT. Entries
// are appended, never moved. Read from blob.s when this file was
// generated.
.label BLOB_UCI_INIT              = $04
.label BLOB_UCI_EXEC_BLOCK        = $07
.label BLOB_UCI_ABORT             = $0A
.label BLOB_UCI_PRESENT           = $0D
.label BLOB_UCI_IDENT             = $10
.label BLOB_UCI_SET_TIMEOUT_A     = $13
.label BLOB_UCI_GET_TIMEOUT_A     = $16
.label BLOB_UCI_LAST_CODE         = $19
.label BLOB_ULTIMATE_INIT         = $1C
.label BLOB_ULTIMATE_AVAILABLE    = $1F
.label BLOB_ULTIMATE_DETECT       = $22
.label BLOB_ULTIMATE_IDENTIFY     = $25
.label BLOB_ULTIMATE_GET_MODEL    = $28
.label BLOB_ULTIMATE_STRERROR     = $2B
.label BLOB_UCI_REQ_CLEAR         = $2E
.label BLOB_UCI_DECODE            = $31
.label BLOB_UCI_STATUS_FMT        = $34
.label BLOB_ULTIMATE_PALETTE_GET  = $37
.label BLOB_ULTIMATE_PALETTE_SET  = $3A
.label BLOB_ULTIMATE_PALETTE_SET_COLOR = $3D
.label BLOB_ULTIMATE_PALETTE_RESET = $40
.label BLOB_ULTIMATE_TURBO_AVAILABLE = $43
.label BLOB_ULTIMATE_TURBO_GET    = $46
.label BLOB_ULTIMATE_TURBO_SET    = $49
.label BLOB_ULTIMATE_TURBO_BADLINES = $4C
.label BLOB_CHDIR                 = $4F
.label BLOB_GETPATH               = $52
.label BLOB_OPENDIR               = $55
.label BLOB_READDIR               = $58
.label BLOB_OPEN                  = $5B
.label BLOB_CLOSE                 = $5E
.label BLOB_READ                  = $61
.label BLOB_WRITE                 = $64
.label BLOB_SEEK                  = $67
.label BLOB_DELETE                = $6A
.label BLOB_LOAD                  = $6D
.label BLOB_BLOAD                 = $70
.label BLOB_SAVE                  = $73
.label BLOB_REU_AVAILABLE         = $76
.label BLOB_REU_STASH             = $79
.label BLOB_REU_FETCH             = $7C
.label BLOB_REU_LOAD              = $7F
.label BLOB_REU_SAVE              = $82
.label BLOB_NET_IFCOUNT           = $85
.label BLOB_NET_MACADDR           = $88
.label BLOB_NET_IPCONFIG          = $8B
.label BLOB_NET_CONNECT           = $8E
.label BLOB_NET_UDP               = $91
.label BLOB_NET_CLOSE             = $94
.label BLOB_NET_READ              = $97
.label BLOB_NET_WRITE             = $9A
.label BLOB_HTTP_GET              = $9D
.label BLOB_HTTP_OPEN             = $A0
.label BLOB_HTTP_HEADER           = $A3
.label BLOB_HTTP_EXCHANGE         = $A6
.label BLOB_HTTP_CLOSE            = $A9
.label BLOB_HTTP_FREE_ALL         = $AC
.label BLOB_REU_SIZE              = $AF
.label BLOB_LEGACY_SID_INFO       = $B2
.label BLOB_STAT                  = $B5
.label BLOB_FSTAT                 = $B8
.label BLOB_RENAME                = $BB
.label BLOB_COPY                  = $BE
.label BLOB_MKDIR                 = $C1
.label BLOB_HOME                  = $C4
.label BLOB_MOUNT                 = $C7
.label BLOB_UNMOUNT               = $CA
.label BLOB_SWAP                  = $CD
.label BLOB_GET_TIME              = $D0
.label BLOB_SET_TIME              = $D3
.label BLOB_REBOOT                = $D6
.label BLOB_FREEZE                = $D9
.label BLOB_DRIVE_ENABLE          = $DC
.label BLOB_DRIVE_POWER           = $DF
.label BLOB_DRIVE_INFO            = $E2
.label BLOB_RAMDISK_INFO          = $E5
.label BLOB_NET_SETIP             = $E8
.label BLOB_HTTP_BODY             = $EB
.label BLOB_HTTP_BODY_FREE        = $EE
.label BLOB_HTTP_BODY_CLEAR       = $F1
.label BLOB_HTTP_BODY_INT         = $F4
.label BLOB_HTTP_BODY_BOOL        = $F7
.label BLOB_HTTP_BODY_STRING      = $FA
.label BLOB_HTTP_BODY_BINARY      = $FD
.label BLOB_ULTIMATE_AUDIO_INIT   = $02E8
.label BLOB_ULTIMATE_AUDIO_AVAILABLE = $02EB
.label BLOB_ULTIMATE_AUDIO_VERSION = $02EE
.label BLOB_AUDIO_CONFIGURE       = $02F1
.label BLOB_AUDIO_START           = $02F4
.label BLOB_AUDIO_STOP            = $02F7
.label BLOB_ULTIMATE_AUDIO_IRQ_STATUS = $02FA
.label BLOB_AUDIO_IRQ_CLEAR       = $02FD
.label BLOB_AUDIO_LOAD_WAV        = $0300

// ---- Blob parameter block ----
// Fields of the blob's parameter block, also from the blob's base: sta
// BLOB + BLOB_BP_ADDR. The block starts at BLOB_PARAMS.
.label BLOB_PARAMS                = $0100  // the parameter block itself
.label BLOB_BP_RESULT             = $0100
.label BLOB_BP_DEVCODE            = $0101
.label BLOB_BP_ADDR               = $0103
.label BLOB_BP_LEN                = $0105
.label BLOB_BP_END                = $0107
.label BLOB_BP_STATUS             = $0109
.label BLOB_BP_NAME               = $0129
.label BLOB_BP_REPLY              = $0151
.label BLOB_BP_ATTRIB             = $0251
.label BLOB_BP_POS                = $0252
.label BLOB_BP_REU                = $0256
.label BLOB_BP_REULEN             = $025A
.label BLOB_BP_SOCK               = $025E
.label BLOB_BP_IFACE              = $025F
.label BLOB_BP_PORT               = $0260
.label BLOB_BP_HTTP               = $0262
.label BLOB_BP_BODY               = $0263
.label BLOB_BP_VERB               = $0264
.label BLOB_BP_NAME2              = $0265
.label BLOB_BP_DRIVE              = $028D
.label BLOB_BP_FORMAT             = $028E
.label BLOB_BP_FLAG               = $028F
.label BLOB_BP_VAL                = $0290
.label BLOB_BP_TIME               = $0294
.label BLOB_BP_AUDIO              = $029A
