/* Generated by tools/gen_protocol.py - DO NOT EDIT BY HAND. */
/* Ultimate Command Interface protocol constants. See docs/uci.md. */

#ifndef ULTIMATE_UCI_PROTOCOL_H
#define ULTIMATE_UCI_PROTOCOL_H

/* ---- Register map ---- */
/* UCI I/O registers. The block is mapped at $DF1B-$DF1F and overlays the */
/* last five REU registers. Mapping is optional and is enabled in the */
/* Ultimate 'Command Interface' configuration menu. */
#define UCI_REG_BUSID    0xDF1B  /* R   SoftwareIEC bus ID (0 = unset) */
#define UCI_REG_CONTROL  0xDF1C  /* W   Control register */
#define UCI_REG_STATUS   0xDF1C  /* R   Status register */
#define UCI_REG_CMDDATA  0xDF1D  /* W   Command data (write command bytes here) */
#define UCI_REG_IDENT    0xDF1D  /* R   Identification register */
#define UCI_REG_RESPDATA 0xDF1E  /* R   Response data queue */
#define UCI_REG_STATDATA 0xDF1F  /* R   Status data queue */

/* ---- Identification register values ---- */
/* Read from UCI_REG_IDENT. */
#define UCI_IDENT_IDLE  0xC9  /* No interrupt pending */
#define UCI_IDENT_IRQ   0x49  /* Interrupt active (bit 7 cleared). FW 3.15+ */
#define UCI_IDENT_MASK  0x7F  /* Mask off the IRQ bit before comparing */
#define UCI_IDENT_VALUE 0x49  /* Expected value after masking with UCI_IDENT_MASK */

/* ---- Control register bits ---- */
/* Write-only. Always write a literal mask; never read-modify-write, */
/* because reading $DF1C returns the status register, not the control */
/* register. */
#define UCI_CTRL_PUSH_CMD 0x01  /* Submit the buffered command */
#define UCI_CTRL_DATA_ACC 0x02  /* Acknowledge / release the current data block */
#define UCI_CTRL_ABORT    0x04  /* Request abort of the running command */
#define UCI_CTRL_CLR_ERR  0x08  /* Clear the state-error flag */
#define UCI_CTRL_IRQ      0x20  /* Raise IRQ on completion (FW 3.15+, latched on push) */
#define UCI_CTRL_TRIGGER  0x40  /* Freeze the machine on the next $FF00 write (latched on push). NOT a transfer accelerator */
#define UCI_CTRL_DMA      0x80  /* Freeze the machine immediately (latched on push). NOT a transfer accelerator - see docs/uci.md */

/* ---- Status register bits ---- */
/* Read from $DF1C. */
#define UCI_STAT_CMD_BUSY 0x01  /* A command is pending in command memory */
#define UCI_STAT_DATA_ACC 0x02  /* Data acknowledge seen by the Ultimate */
#define UCI_STAT_ABORT_P  0x04  /* Abort request still pending */
#define UCI_STAT_ERROR    0x08  /* State error: command pushed while not idle */
#define UCI_STAT_STATE    0x30  /* Protocol state mask */
#define UCI_STAT_STAT_AV  0x40  /* Status byte available at $DF1F */
#define UCI_STAT_DATA_AV  0x80  /* Response byte available at $DF1E */

/* ---- Protocol states ---- */
/* Value of (status & UCI_STAT_STATE). */
#define UCI_STATE_IDLE      0x00  /* Ready to accept a command */
#define UCI_STATE_BUSY      0x10  /* Command submitted, Ultimate is working */
#define UCI_STATE_DATA_LAST 0x20  /* Data available, this is the final block */
#define UCI_STATE_DATA_MORE 0x30  /* Data available, more blocks follow */

/* ---- Queue sizes ---- */
/* Hard limits enforced by the hardware. The three queue pointers all */
/* saturate on the LAST byte of their buffer rather than one past it, which */
/* costs a byte on the way in and can hang a naive reader on the way out - */
/* see docs/uci.md, 'Queue pointer saturation'. */
#define UCI_MAX_COMMAND        896  /* Command queue size in bytes ($380) */
#define UCI_MAX_RESPONSE       896  /* Response data queue size in bytes ($380) */
#define UCI_MAX_STATUS         256  /* Status queue size in bytes ($100) */
#define UCI_MAX_COMMAND_USABLE 895  /* Largest command the hardware can actually receive */

/* ---- Timeouts ---- */
/* Budget for a status poll loop, in units of 256 polls. The core installs */
/* the default at bring-up, so the bounded-time guarantee holds without the */
/* caller doing anything; raise it around a command whose duration cannot */
/* be bounded and restore it after. */
#define UCI_TIMEOUT_DEFAULT 200  /* Comfortable for local commands at any CPU speed */
#define UCI_TIMEOUT_FOREVER 0  /* Poll until the Ultimate answers, however long that takes */

/* ---- Targets ---- */
/* First byte of every command. Only bits 0-3 select the target; bit 7 is */
/* the NO_REPLY flag (INFERRED from firmware). */
#define UCI_TARGET_MASK     0x0F  /* Target field of the first command byte */
#define UCI_TARGET_NO_REPLY 0x80  /* Fire-and-forget: skip the data/status phase */
#define UCI_TARGET_DOS1     0x01  /* Ultimate DOS instance 1 */
#define UCI_TARGET_DOS2     0x02  /* Ultimate DOS instance 2 */
#define UCI_TARGET_NETWORK  0x03  /* Network (TCP/UDP sockets) */
#define UCI_TARGET_CONTROL  0x04  /* Machine / cartridge control */
#define UCI_TARGET_SOFTIEC  0x05  /* SoftwareIEC bypass */
#define UCI_TARGET_HTTP     0x06  /* HTTP client (FW 3.15+) */
#define UCI_TARGET_MAX      0x0F  /* Highest addressable target */

/* ---- Commands common to every target ---- */
#define UCI_CMD_IDENTIFY 0x01  /* Return an identification string. Cannot fail. */

/* ---- Ultimate DOS commands (targets $01/$02) ---- */
#define DOS_CMD_IDENTIFY       0x01
#define DOS_CMD_OPEN_FILE      0x02  /* <attrib> <filename> - attrib is a DOS_FA_* mask */
#define DOS_CMD_CLOSE_FILE     0x03
#define DOS_CMD_READ_DATA      0x04  /* <len:16> - arrives as 512-byte blocks; uci_exec walks the chain */
#define DOS_CMD_WRITE_DATA     0x05  /* $00 $00 <data...> - the two fixed bytes are skipped, not stored */
#define DOS_CMD_FILE_SEEK      0x06  /* <pos:32> */
#define DOS_CMD_FILE_INFO      0x07
#define DOS_CMD_FILE_STAT      0x08  /* <filename> */
#define DOS_CMD_DELETE_FILE    0x09  /* <filename> */
#define DOS_CMD_RENAME_FILE    0x0A  /* <old> $00 <new> */
#define DOS_CMD_COPY_FILE      0x0B  /* <src> $00 <dst> */
#define DOS_CMD_CHANGE_DIR     0x11  /* <dirname> */
#define DOS_CMD_GET_PATH       0x12
#define DOS_CMD_OPEN_DIR       0x13
#define DOS_CMD_READ_DIR       0x14
#define DOS_CMD_COPY_UI_PATH   0x15  /* Deprecated since FW 3.0 */
#define DOS_CMD_CREATE_DIR     0x16  /* <dirname> */
#define DOS_CMD_COPY_HOME_PATH 0x17
#define DOS_CMD_LOAD_REU       0x21  /* <addr:32> <len:32> - the safe REU pair; never wrap the control pair, see #740 */
#define DOS_CMD_SAVE_REU       0x22  /* <addr:32> <len:32> - the safe REU pair; never wrap the control pair, see #740 */
#define DOS_CMD_MOUNT_DISK     0x23  /* <id> <filename> */
#define DOS_CMD_UMOUNT_DISK    0x24  /* <id> */
#define DOS_CMD_SWAP_DISK      0x25  /* <id> */
#define DOS_CMD_GET_TIME       0x26  /* <fmt> - fmt may be omitted; the target defaults it to $00 */
#define DOS_CMD_SET_TIME       0x27  /* <year_1900> <month> <day> <hour> <minute> <second> - year is the year minus 1900 */
#define DOS_CMD_ECHO           0xF0  /* <data...> - Echo the command back as data */

/* ---- DOS file open attributes ---- */
/* Bit flags for DOS_CMD_OPEN_FILE. */
#define DOS_FA_READ          0x01  /* Open for reading */
#define DOS_FA_WRITE         0x02  /* Open for writing, do not truncate */
#define DOS_FA_CREATE_NEW    0x04  /* Create/truncate to zero bytes */
#define DOS_FA_CREATE_ALWAYS 0x08  /* May overwrite an existing file */

/* ---- DOS directory entry attributes ---- */
/* First byte of each DOS_CMD_READ_DIR entry (FAT semantics). */
#define DOS_ATTR_READONLY 0x01
#define DOS_ATTR_HIDDEN   0x02
#define DOS_ATTR_SYSTEM   0x04
#define DOS_ATTR_VOLUME   0x08
#define DOS_ATTR_DIR      0x10
#define DOS_ATTR_ARCHIVE  0x20

/* ---- Network commands (target $03) ---- */
#define NET_CMD_IDENTIFY            0x01
#define NET_CMD_GET_INTERFACE_COUNT 0x02
#define NET_CMD_GET_NETADDR         0x04  /* <iface> - replies with UCI_NET_MACADDR_BYTES */
#define NET_CMD_GET_IPADDR          0x05  /* <iface> - replies with UCI_NET_IPCONFIG_BYTES, ip/mask/gw */
#define NET_CMD_SET_IPADDR          0x06  /* <iface> <ipconfig...> - ipconfig must be exactly UCI_NET_IPCONFIG_BYTES */
#define NET_CMD_OPEN_TCP            0x07  /* <port:16> <host> */
#define NET_CMD_OPEN_UDP            0x08  /* <port:16> <host> */
#define NET_CMD_CLOSE_SOCKET        0x09  /* <handle> */
#define NET_CMD_READ_SOCKET         0x10  /* <handle> <len:16> */
#define NET_CMD_WRITE_SOCKET        0x11  /* <handle> <data...> */
#define NET_CMD_LISTEN_START        0x12  /* <port:16> - INFERRED: not in the published spec */
#define NET_CMD_LISTEN_STOP         0x13  /* INFERRED: not in the published spec */
#define NET_CMD_LISTEN_STATE        0x14  /* INFERRED: not in the published spec */
#define NET_CMD_LISTEN_SOCKET       0x15  /* INFERRED: not in the published spec */

/* ---- Network address sizes ---- */
/* Fixed-width blobs the network target exchanges. */
#define UCI_NET_MACADDR_BYTES  6  /* bytes in a MAC address */
#define UCI_NET_IPCONFIG_BYTES 12  /* bytes in an ip/mask/gateway triple */
#define UCI_NET_READ_PREFIX    2  /* 16-bit count the firmware puts in front of socket data */
#define UCI_NET_READ_MAX       512  /* largest READ_SOCKET this SDK will ask for - see docs/uci.md */
#define UCI_NET_NO_DATA        65535  /* that count, when nothing was available to read */
#define UCI_NET_DEV_OK         0  /* network device code: the reply carries data */
#define UCI_NET_DEV_CLOSED     1  /* network device code: the peer hung up, reported once */
#define UCI_NET_DEV_NO_DATA    2  /* network device code: nothing pending, try again */

/* ---- Control commands (target $04) ---- */
#define CTRL_CMD_IDENTIFY          0x01
#define CTRL_CMD_READ_RTC          0x02  /* INFERRED: firmware only, not in the published spec */
#define CTRL_CMD_FINISH_CAPTURE    0x03
#define CTRL_CMD_FREEZE            0x05
#define CTRL_CMD_REBOOT            0x06  /* Never replies: the C64 and the UCI are reset */
#define CTRL_CMD_LOAD_REU          0x08  /* <filename> - never returns on FW 3.14d and wedges the interface, see #740 */
#define CTRL_CMD_SAVE_REU          0x09  /* <filename> */
#define CTRL_CMD_U64_SAVEMEM       0x0F  /* <filename> - U64 family only */
#define CTRL_CMD_DECODE_TRACK      0x11  /* GCR -> binary in REU */
#define CTRL_CMD_ENCODE_TRACK      0x12  /* INFERRED: firmware only, not in the published spec */
#define CTRL_CMD_EASYFLASH         0x20  /* $00 <bank> <baseaddr> - sector erase; baseaddr bit $20 selects the high ROM */
#define CTRL_CMD_GET_HWINFO        0x28  /* <sub> - sub may be omitted; the target defaults it to CTRL_HWINFO_MODEL */
#define CTRL_CMD_GET_DRVINFO       0x29  /* <effective_addr> */
#define CTRL_CMD_ENABLE_DRIVE_A    0x30
#define CTRL_CMD_DISABLE_DRIVE_A   0x31
#define CTRL_CMD_ENABLE_DRIVE_B    0x32
#define CTRL_CMD_DISABLE_DRIVE_B   0x33
#define CTRL_CMD_GET_DRIVE_A_POWER 0x34
#define CTRL_CMD_GET_DRIVE_B_POWER 0x35
#define CTRL_CMD_GET_RAMDISKINFO   0x40  /* GEOS MegaPatch 3 RAM disk layout */
#define CTRL_CMD_LOAD_CONFIG       0x50  /* INFERRED: firmware only, not in the published spec */
#define CTRL_CMD_GET_PALETTE       0x51  /* -> 48 RGB bytes (FW > 3.15) */
#define CTRL_CMD_SET_PALETTE       0x52  /* <palette...> - palette is exactly UCI_PALETTE_BYTES (FW > 3.15) */
#define CTRL_CMD_SET_PALETTE_COLOR 0x53  /* <index> <r> <g> <b> - (FW > 3.15) */
#define CTRL_CMD_RESET_PALETTE     0x54  /* restore the built-in palette (FW > 3.15) */

/* ---- Control: VIC-II palette ---- */
/* Runtime palette control. Affects the live palette only; it does not */
/* touch flash configuration or VPL files. */
#define UCI_PALETTE_COLORS 16  /* colors in a VIC-II palette */
#define UCI_PALETTE_BYTES  48  /* bytes in a full palette frame (16 * RGB) */

/* ---- Control: hardware info sub-commands ---- */
#define CTRL_HWINFO_MODEL 0x00  /* ASCII model name, e.g. 'ULTIMATE 64' */
#define CTRL_HWINFO_SID   0x01  /* SID configuration frames */

/* ---- Control: drive type codes ---- */
/* From CTRL_CMD_GET_DRVINFO. */
#define CTRL_DRVTYPE_1541      0x00
#define CTRL_DRVTYPE_1571      0x01
#define CTRL_DRVTYPE_1581      0x02
#define CTRL_DRVTYPE_UNDECIDED 0x03
#define CTRL_DRVTYPE_SOFTIEC   0x0F
#define CTRL_DRVTYPE_PRINTER   0x50

/* ---- SoftwareIEC commands (target $05) ---- */
#define SOFTIEC_CMD_IDENTIFY      0x01  /* answers in ASCII; every other command on this target answers in binary */
#define SOFTIEC_CMD_LOAD_SU       0x10  /* <sec> <verify> <addr:16> <unused:16> <name> - sec 1 uses the file's own load address, 0 uses addr; unused is never read but must be sent */
#define SOFTIEC_CMD_LOAD_EX       0x11  /* <sec> <verify> - returns the end address in status bytes 1-2 */
#define SOFTIEC_CMD_SAVE          0x12  /* <verify> <sec> <start:16> <end:16> <name> */
#define SOFTIEC_CMD_OPEN          0x13  /* <sec> $00 <name> */
#define SOFTIEC_CMD_CLOSE         0x14  /* <sec> */
#define SOFTIEC_CMD_CHKIN         0x15  /* <sec> */
#define SOFTIEC_CMD_CHKOUT        0x16  /* <sec> $00 <data...> - sec & $F0 of $F0 opens and $E0 closes; anything else pushes data */
#define SOFTIEC_CMD_ADD_PARTITION 0x20  /* <index> <ident_colon_path> - the string is 'IDENT:/path' */
#define SOFTIEC_CMD_DEL_PARTITION 0x21  /* <index> */
#define SOFTIEC_CMD_GET_FATNAME   0x22  /* <channel> <iec_name> - resolves an IEC name to a host path */
#define SOFTIEC_CMD_GET_IECNAME   0x23  /* <fat_name> */

/* ---- SoftwareIEC status bytes ---- */
/* This target returns a single binary status byte, not an ASCII status */
/* string. */
#define SOFTIEC_ST_OK                0x00
#define SOFTIEC_ST_FILE_NOT_FOUND    0x01
#define SOFTIEC_ST_SAVE_ERROR        0x02
#define SOFTIEC_ST_NO_INPUT_CHANNEL  0x03
#define SOFTIEC_ST_UNKNOWN_COMMAND   0x04
#define SOFTIEC_ST_MODULE_NOT_LOADED 0x05
#define SOFTIEC_ST_INVALID_PARAMS    0x06
#define SOFTIEC_ST_INVALID_NAME      0x07
#define SOFTIEC_ST_INVALID_PARTITION 0x08
#define SOFTIEC_ST_INVALID_DIRECTORY 0x09
#define SOFTIEC_ST_VERIFY_ERROR      0x80  /* LOAD_EX verify mismatch */

/* ---- HTTP commands (target $06, FW 3.15+) ---- */
#define HTTP_CMD_IDENTIFY        0x01
#define HTTP_CMD_FREE_ALL        0x10
#define HTTP_CMD_HEADER_CREATE   0x11  /* <verb> <url> - verb is an HTTP_VERB_* code */
#define HTTP_CMD_HEADER_FREE     0x12  /* <handle> */
#define HTTP_CMD_HEADER_ADD      0x13  /* <handle> <key_colon_value> - the string is 'key: value' */
#define HTTP_CMD_HEADER_QUERY    0x14  /* <handle> <key> */
#define HTTP_CMD_HEADER_LIST     0x15  /* <handle> <index> */
#define HTTP_CMD_BODY_CREATE     0x21  /* <format> - format is an HTTP_BODY_* code */
#define HTTP_CMD_BODY_FREE       0x22  /* <handle> */
#define HTTP_CMD_BODY_ADD_INT    0x23  /* <handle> <key:len> <key> <value:32> - 1 to 4 value bytes are accepted, sign-extended from the last; send four */
#define HTTP_CMD_BODY_ADD_BOOL   0x24  /* <handle> <key:len> <key> <value> - any non-zero value is true */
#define HTTP_CMD_BODY_ADD_STRING 0x25  /* <handle> <key:len> <key> <value:len> <value> */
#define HTTP_CMD_BODY_ADD_OBJECT 0x26  /* <handle> <key:len> <key> */
#define HTTP_CMD_BODY_ADD_ARRAY  0x27  /* <handle> <key:len> <key> */
#define HTTP_CMD_BODY_UP         0x28  /* <handle> */
#define HTTP_CMD_BODY_REMOVE     0x29  /* <handle> <path> */
#define HTTP_CMD_BODY_QUERY      0x2A  /* <handle> <path> */
#define HTTP_CMD_BODY_MOVE       0x2B  /* <handle> <path> */
#define HTTP_CMD_BODY_ADD_BINARY 0x2C  /* <handle> <data...> */
#define HTTP_CMD_BODY_ADD        0x2D  /* <handle> <items...> */
#define HTTP_CMD_BODY_CLEAR      0x2E  /* <handle> */
#define HTTP_CMD_DO_EXCHANGE_OBJ 0x31  /* <header> <body> - pass HTTP_BODY_NONE as body to send none */
#define HTTP_CMD_DO_EXCHANGE_RAW 0x32  /* <header> <body> - pass HTTP_BODY_NONE as body to send none */

/* ---- HTTP verbs ---- */
#define HTTP_VERB_GET     0x01
#define HTTP_VERB_PUT     0x02
#define HTTP_VERB_POST    0x03
#define HTTP_VERB_PATCH   0x04
#define HTTP_VERB_DELETE  0x05
#define HTTP_VERB_HEAD    0x06
#define HTTP_VERB_OPTIONS 0x07
#define HTTP_VERB_CONNECT 0x08
#define HTTP_VERB_TRACE   0x09

/* ---- HTTP body formats ---- */
#define HTTP_BODY_BINARY      0x01
#define HTTP_BODY_JSON_OBJECT 0x02
#define HTTP_BODY_JSON_ARRAY  0x03
#define HTTP_BODY_URL_ENCODED 0x04
#define HTTP_BODY_NONE        0xFF  /* Pass as <body> to send no body */

/* ---- HTTP / JSON value type tags ---- */
/* Used by BODY_ADD and BODY_QUERY. */
#define HTTP_TYPE_INT    0x01  /* 4 bytes, LSB first */
#define HTTP_TYPE_BOOL   0x02  /* 1 byte */
#define HTTP_TYPE_STRING 0x03  /* <len> <bytes> */
#define HTTP_TYPE_OBJECT 0x04  /* <count> [<key> <value>]* */
#define HTTP_TYPE_ARRAY  0x05  /* <count> [<value>]* */

/* ---- Ultimate 64 turbo control (NOT UCI) ---- */
/* The one part of the machine the SDK reaches without the command */
/* interface, because there is no UCI command for CPU speed. Plain memory- */
/* mapped registers, documented at 1541u-documentation.readthedocs.io. They */
/* answer $FF unless the Ultimate's 'Turbo Control' setting is 'U64 Turbo */
/* Registers' or 'Turbo Enable Bit', which is what makes availability */
/* testable rather than assumed. */
#define U64_REG_TURBO         53297  /* R/W  bits 0-3 speed index, bit 7 badlines off */
#define U64_REG_TURBO_ENABLE  53296  /* R/W  bit 0, in 'Turbo Enable Bit' mode only */
#define U64_TURBO_SPEED_MASK  0x0F  /* speed index field of U64_REG_TURBO */
#define U64_TURBO_NO_BADLINES 0x80  /* set to stop the VIC stealing cycles */
#define U64_TURBO_UNAVAILABLE 0xFF  /* what both registers read when turbo is off in config */

/* ---- REU registers (NOT UCI) ---- */
/* The second and last thing the SDK reaches without the command interface, */
/* for the same reason as turbo: no UCI command moves bytes between C64 RAM */
/* and the REU. The register set is the 1750's, implemented in */
/* fpga/cart_slot/vhdl_source/reu.vhd, and the command interface overlays */
/* $DF1B-$DF1F above it - the REU decodes $DF00-$DF17 only, so the two */
/* coexist. A transfer runs under DMA with the CPU halted, so it is */
/* finished by the time the next instruction runs. */
#define REU_REG_STATUS   57088  /* R    bit 7 IRQ, 6 done, 5 verify error, 4 size; reading clears 6 and 5 */
#define REU_REG_COMMAND  57089  /* R/W  bit 7 execute, 5 autoload, 4 start now, bits 1-0 mode */
#define REU_REG_C64_LO   57090  /* R/W  C64 base address, low */
#define REU_REG_C64_HI   57091  /* R/W  C64 base address, high */
#define REU_REG_ADDR_LO  57092  /* R/W  REU base address, low */
#define REU_REG_ADDR_MID 57093  /* R/W  REU base address, middle */
#define REU_REG_ADDR_HI  57094  /* R/W  REU base address, high */
#define REU_REG_LEN_LO   57095  /* R/W  transfer length, low */
#define REU_REG_LEN_HI   57096  /* R/W  transfer length, high; 0 means 65536 */
#define REU_REG_IRQMASK  57097  /* R/W  bit 7 enable, 6 on done, 5 on verify error */
#define REU_REG_CONTROL  57098  /* R/W  bit 7 fix C64 address, bit 6 fix REU address */

/* ---- REU command and status bits ---- */
/* Written to REU_REG_COMMAND and read back from REU_REG_STATUS. */
/* REU_CMD_NOW is not optional for a program driving the REU itself: with */
/* it clear the transfer waits for a write to $FF00, which is the trick a */
/* cartridge uses and a nuisance everywhere else. */
#define REU_CMD_EXECUTE       0x80  /* start the transfer */
#define REU_CMD_AUTOLOAD      0x20  /* reload address and length after it finishes */
#define REU_CMD_NOW           0x10  /* start now rather than on a write to $FF00 */
#define REU_MODE_STASH        0x00  /* C64 -> REU */
#define REU_MODE_FETCH        0x01  /* REU -> C64 */
#define REU_MODE_SWAP         0x02  /* exchange both ways */
#define REU_MODE_VERIFY       0x03  /* compare without writing anything */
#define REU_STAT_DONE         0x40  /* the transfer finished; cleared by reading the register */
#define REU_STAT_VERIFY_ERROR 0x20  /* a verify found a difference */
#define REU_STAT_SIZE         0x10  /* set on 256K and larger */

/* ---- Ultimate 64 speed indices ---- */
/* Index into the machine's speed table. **Only these four mean the same */
/* thing on both machines.** The U64 runs 1,2,3,4,5,6,8..48 MHz and the */
/* U64-II runs 1,2,3,4,6,8..64, so index 4 is 5 MHz on one and 6 MHz on the */
/* other. Above 4 MHz, ask for an index and you get whatever that machine's */
/* table says. */
#define U64_SPEED_1MHZ 0  /* stock C64 speed, and what turbo_off restores */
#define U64_SPEED_2MHZ 1
#define U64_SPEED_3MHZ 2
#define U64_SPEED_4MHZ 3  /* the fastest index that means the same on both */
#define U64_SPEED_MAX  15  /* whatever the machine's top speed is: 48 or 64 MHz */

/* ---- SDK status / error codes ---- */
/* Stable across firmware versions. The raw device status is preserved */
/* separately, see uci_last_device_code(). */
#define ULTIMATE_OK                   0  /* Success (device may still have set a warning code) */
#define ULTIMATE_ERR_NO_DEVICE        1  /* No Ultimate Command Interface found */
#define ULTIMATE_ERR_TIMEOUT          2  /* The Ultimate did not answer in time */
#define ULTIMATE_ERR_PROTOCOL         3  /* Transport-level protocol violation */
#define ULTIMATE_ERR_NOT_SUPPORTED    4  /* Target or command not implemented by this firmware */
#define ULTIMATE_ERR_INVALID_ARGUMENT 5  /* Bad argument supplied by the caller */
#define ULTIMATE_ERR_IO               6  /* File system / network I/O failure */
#define ULTIMATE_ERR_DEVICE           7  /* Target reported a failure status */
#define ULTIMATE_ERR_TRUNCATED        8  /* Reply did not fit in the caller's buffer */
#define ULTIMATE_ERR_ABORTED          9  /* Command was aborted */
#define ULTIMATE_END                  10  /* No more entries: the end of a directory, not a failure */
#define ULTIMATE_ERR_COUNT            11  /* Number of codes above, for a table that maps them */

/* ---- Request block layout ---- */
/* Byte offsets into a uci_request. The assembly core is the authority on */
/* this layout; bindings/cc65/abi_assert.c fails the build if the C struct */
/* ever stops matching. */
#define UCI_REQ_TARGET     0  /* byte: target id, optionally | UCI_TARGET_NO_REPLY */
#define UCI_REQ_COMMAND    1  /* byte: command code */
#define UCI_REQ_ARGS       2  /* word: pointer to argument bytes, 0 for none */
#define UCI_REQ_ARGLEN     4  /* word: number of argument bytes */
#define UCI_REQ_PAYLOAD    6  /* word: pointer to payload bytes, 0 for none */
#define UCI_REQ_PAYLOADLEN 8  /* word: number of payload bytes */
#define UCI_REQ_DATA       10  /* word: buffer for the reply, 0 to discard it */
#define UCI_REQ_DATAMAX    12  /* word: size of that buffer */
#define UCI_REQ_DATALEN    14  /* word: out, reply bytes stored */
#define UCI_REQ_STATUS     16  /* word: buffer for the status string, 0 to discard */
#define UCI_REQ_STATUSMAX  18  /* word: size of that buffer */
#define UCI_REQ_STATUSLEN  20  /* word: out, status bytes stored */
#define UCI_REQ_SIZE       22  /* total size of the block */

/* ---- SDK memory footprint ---- */
/* How much RAM the core needs, and where. All of it is placeable: see */
/* UCI_ZP and UCI_VARS in docs/asm-abi.md. */
#define UCI_ZP_SIZE   4  /* zero page bytes the core needs */
#define UCI_VARS_SIZE 125  /* non-zero-page bytes the whole SDK needs */

/* ---- ASCII literals ---- */
/* Bytes that come off the wire are always written numerically. An */
/* assembler charmap, or a compiler's idea of the target character set, */
/* must never reach them: cc65 turns "NO TARGET" into PETSCII, which */
/* silently stops matching what the Ultimate sends. */
#define UCI_ASCII_ZERO  0x30  /* '0' */
#define UCI_ASCII_NINE  0x39  /* '9' */
#define UCI_ASCII_COMMA 0x2C  /* ',' */
#define UCI_ASCII_SPACE 0x20  /* ' ' */

/* ---- Status string families ---- */
/* Targets do not agree on how status is encoded; the SDK picks a decoder */
/* per target. */
#define UCI_STATUS_FMT_DECIMAL2 0  /* 'NN,TEXT' - DOS, Network, Control */
#define UCI_STATUS_FMT_DECIMAL3 1  /* 'NNN TEXT' - HTTP */
#define UCI_STATUS_FMT_BINARY   2  /* single binary byte - SoftwareIEC */
#define UCI_STATUS_FMT_NONE     3  /* target sends no status */

/* ---- Protocol strings ---- */
/*
 * Protocol strings are emitted as explicit byte lists, never as C string
 * literals. cc65 translates literals into the target character set, so
 * "NO TARGET" compiled for the C64 becomes PETSCII and stops matching the
 * ASCII the Ultimate actually sends. Use them as:
 *
 *     static const uint8_t marker[] = { UCI_STR_NO_TARGET_BYTES };
 */
/* UCI_STR_NO_TARGET = "NO TARGET": Reply of the built-in placeholder target: this target ID is not implemented. */
#define UCI_STR_NO_TARGET_BYTES 0x4E, 0x4F, 0x20, 0x54, 0x41, 0x52, 0x47, 0x45, 0x54
#define UCI_STR_NO_TARGET_LEN 9
/* UCI_STR_STATUS_OK = "00,OK": Canonical success status of the decimal2 family. */
#define UCI_STR_STATUS_OK_BYTES 0x30, 0x30, 0x2C, 0x4F, 0x4B
#define UCI_STR_STATUS_OK_LEN 5

#endif /* ULTIMATE_UCI_PROTOCOL_H */
